version: 2
jobs:
  build:
    docker: &docker
      - image: circleci/golang:1.11.1
        environment:
          GO111MODULE: "on"
    working_directory: &working_directory /go/src/github.com/sawadashota/gh-issue
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Build
          command: go build github.com/sawadashota/gh-issue/cmd/gh-issue
      - persist_to_workspace:
          root: .
          paths:
            - .
  release:
    docker: *docker
    working_directory: *working_directory
    steps:
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Install goreleaser
          working_directory: /go
          environment:
            GO111MODULE: "off"
          command: go get -u github.com/goreleaser/goreleaser
      - run:
          name: Release
          working_directory: *working_directory
          environment:
            GO111MODULE: "on"
          command: goreleaser
workflows:
  version: 2
  default:
    jobs:
      - build
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
